version: "3.7"
services:
  agile-ui-app:
    restart: always
    image: yippeecai/agile-ui-app:latest
    networks:
      - agile-suite
    ports:
      - "3010:80"
    volumes:
      - ./log:/var/log
    depends_on:
      - agile-mock-api
        
  agile-mock-api:
    restart: always
    image: yippeecai/agile-mock-api:latest
    networks:
      - agile-suite
    ports:
      - "15000:5000"
    volumes:
      - ./export:/app/export
      - ./public/data:/app/public/data
      - ./public/images:/app/public/images

networks:
  agile-suite:
    driver: bridge
